import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { Layout } from "y/components/Layout";
import CompassDemo from "../components/CompassDemo";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Layout title="Compass" tableOfContents={[]}>
        <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
          <CompassDemo />
        </main>
      </Layout>
    </>
  );
};

export default Home;
